<?php

return array(
    'GitlabCI\Exception\ValidationFailedException' => __DIR__ . '/src/GitlabCI/Exception/ValidationFailedException.php',
    'GitlabCI\Exception\LogicException' => __DIR__ . '/src/GitlabCI/Exception/LogicException.php',
    'GitlabCI\Exception\MissingArgumentException' => __DIR__ . '/src/GitlabCI/Exception/MissingArgumentException.php',
    'GitlabCI\Exception\ErrorException' => __DIR__ . '/src/GitlabCI/Exception/ErrorException.php',
    'GitlabCI\Exception\RuntimeException' => __DIR__ . '/src/GitlabCI/Exception/RuntimeException.php',
    'GitlabCI\Exception\InvalidArgumentException' => __DIR__ . '/src/GitlabCI/Exception/InvalidArgumentException.php',
    'GitlabCI\Model\Build' => __DIR__ . '/src/GitlabCI/Model/Build.php',
    'GitlabCI\Model\Runner' => __DIR__ . '/src/GitlabCI/Model/Runner.php',
    'GitlabCI\Model\Project' => __DIR__ . '/src/GitlabCI/Model/Project.php',
    'GitlabCI\Model\AbstractModel' => __DIR__ . '/src/GitlabCI/Model/AbstractModel.php',
    'GitlabCI\HttpClient\HttpClient' => __DIR__ . '/src/GitlabCI/HttpClient/HttpClient.php',
    'GitlabCI\HttpClient\HttpClientInterface' => __DIR__ . '/src/GitlabCI/HttpClient/HttpClientInterface.php',
    'GitlabCI\HttpClient\Listener\ErrorListener' => __DIR__ . '/src/GitlabCI/HttpClient/Listener/ErrorListener.php',
    'GitlabCI\HttpClient\Listener\AuthListener' => __DIR__ . '/src/GitlabCI/HttpClient/Listener/AuthListener.php',
    'GitlabCI\HttpClient\Message\Request' => __DIR__ . '/src/GitlabCI/HttpClient/Message/Request.php',
    'GitlabCI\HttpClient\Message\Response' => __DIR__ . '/src/GitlabCI/HttpClient/Message/Response.php',
    'GitlabCI\Api\ApiInterface' => __DIR__ . '/src/GitlabCI/Api/ApiInterface.php',
    'GitlabCI\Api\AbstractApi' => __DIR__ . '/src/GitlabCI/Api/AbstractApi.php',
    'GitlabCI\Api\Builds' => __DIR__ . '/src/GitlabCI/Api/Builds.php',
    'GitlabCI\Api\Runners' => __DIR__ . '/src/GitlabCI/Api/Runners.php',
    'GitlabCI\Api\Projects' => __DIR__ . '/src/GitlabCI/Api/Projects.php',
    'Gitlab\Client' => __DIR__ . '/src/GitlabCI/Client.php',
);
